language: android
jdk:
  - oraclejdk8
sudo: required
dist: trusty
env:
  global:
    - BRANCH_NAME=master
    - ANDROID_BUILD_TOOLS=29.0.3
android:
  components:
    - android-29
    - build-tools-$ANDROID_BUILD_TOOLS
    - extra-google-google_play_services
  licenses:
    - ".+"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_script:
  - env
script:
  - "./firebase.sh"
